import { createApp } from 'vue'
import RootApp from './RootApp.vue'
import { router } from './router'
import './styles.css'
import './timeline-enhancements.css'
import './asset-timeline.css'
import './editor-workflow.css'
import './workflow-v4.css'
import './workflow-v5.css'
import './motion-animations.css'
import './capcut-layout.css'
import './upload-dialog.css'
import './upload-auto-layout.css'
import './asset-manager.css'
import './polish-v13.css'

createApp(RootApp).use(router).mount('#app')
